<?php
$sLangName  = "Deutsch";
$iLangNr    = 0;
$aLang = array(
    'charset'                 => 'UTF-8',
    
    'jxsales_menu'            => 'Artikel-Kunden Analyse',
    'jxsales_menu_latest'     => 'Neueste Bestellungen',
    'tbcluser_jxsales'        => 'Bestellungen',
    'JXSALES_TITLE'           => 'Artikel-Kunden Analyse',
    'JXSALES_SEARCHTERM'      => 'Suchbegriff',
    'JXSALES_LATEST_TITLE'    => 'Neueste Bestellungen',
    'JXSALES_CUSTNO'          => 'Kd-Nr.',
    'JXSALES_VARIANT'         => 'Variante',
    'JXSALES_DOWNLOAD'        => 'Download',
    'JXSALES_PRINT'           => 'Drucken',
    'JXSALES_GOTOPRODUCT'     => 'Artikel anzeigen',
    'JXSALES_GOTOORDER'       => 'Bestellung anzeigen',
    'JXSALES_GOTOUSER'        => 'Benutzer anzeigen',
    'JXSALES_ARTSUM'          => 'Summe',
    'JXSALES_TOTALSUM'        => 'Gesamtsumme',
    'JXSALES_ORDERNO'         => 'Best-Nr.',
    'JXSALES_INVNO'           => 'Re-Nr.',
    'JXSALES_INVTOTAL'        => 'Re-Betrag',

    'SHOP_MODULE_GROUP_JXSALES_DISPLAY'        => 'Anzeige',
    'SHOP_MODULE_bJxSalesDisplayEAN'           => 'EAN anzeigen',
    'SHOP_MODULE_bJxSalesDisplayAddress'       => 'Adresse anzeigen',
    'SHOP_MODULE_bJxSalesDisplayCountry'       => 'Land anzeigen',
    'SHOP_MODULE_sJxSalesSelectLimit'          => 'Max. Anzahl',
    'SHOP_MODULE_GROUP_JXSALES_REPLACE'        => 'Ersetzungen',
    'SHOP_MODULE_sJxSalesReplaceMRS'           => 'Anrede für weibliche Kunden (z.B. "Liebe Frau")',
    'SHOP_MODULE_sJxSalesReplaceMR'            => 'Anrede für männliche Kunden (z.B. "Lieber Herr")',
    'SHOP_MODULE_GROUP_JXSALES_DOWNLOAD'       => 'Download / Export',
    'SHOP_MODULE_bJxSalesHeader'               => 'Spaltenüberschriften exportieren',
    'SHOP_MODULE_sJxSalesSeparator'            => 'Trennzeichen',
    'SHOP_MODULE_sJxSalesSeparator_comma'      => ',&nbsp;&nbsp; (Komma)',
    'SHOP_MODULE_sJxSalesSeparator_semicolon'  => ';&nbsp;&nbsp; (Semikolon)',
    'SHOP_MODULE_sJxSalesSeparator_tab'        => '&rarr; (Tabulator)',
    'SHOP_MODULE_sJxSalesSeparator_pipe'       => '|&nbsp;&nbsp; (Senkrechter Strich)',
    'SHOP_MODULE_sJxSalesSeparator_tilde'      => '&sim;&nbsp; (Tilde)',
    'SHOP_MODULE_bJxSalesQuote'                => 'Spalten mit Anführungszeichen begrenzen',
    'SHOP_MODULE_GROUP_JXSALES_INCLUDESETTINGS'=> 'Benutzerdefinierte Erweiterungen',
    'SHOP_MODULE_aJxSalesIncludeFiles'         => 'Benutzerdefinierte Analyen<br>(je eine Datei pro Zeile) ',
);
?>